import type { Product } from "./types";

/**
 * Single source of truth for the catalog.
 * Adding a product or category = data edit here, no component changes (scalable by design).
 */
export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "airwave-pods-pro",
    name: "Airwave Pods Pro",
    category: "earbuds",
    tagline: "Adaptive ANC. Studio sound. All day.",
    description:
      "Flagship true-wireless earbuds with adaptive active noise cancellation, 45-hour total playback and a spatial audio engine tuned for bass that hits without drowning the mids.",
    priceINR: 4999,
    priceUSD: 79,
    mrpINR: 8999,
    mrpUSD: 129,
    rating: 4.7,
    reviewCount: 2841,
    colors: [
      { name: "Carbon", hex: "#1C1F26" },
      { name: "Blaze Red", hex: "#EE1C25" },
      { name: "Arctic", hex: "#E7EAF0" },
    ],
    features: [
      "Adaptive ANC up to 45dB",
      "45h total with case",
      "Spatial audio engine",
      "Dual-device pairing",
    ],
    specs: [
      { label: "Driver", value: "11mm dynamic" },
      { label: "Battery", value: "9h + 36h case" },
      { label: "Latency", value: "45ms game mode" },
      { label: "Water resist", value: "IPX5" },
    ],
    badges: ["Adaptive ANC", "Bestseller"],
    render: "earbuds",
    featured: true,
    bestseller: true,
    reviews: [
      {
        author: "Aarav M.",
        rating: 5,
        title: "Punchy but balanced",
        body: "The ANC genuinely cuts the metro noise and the bass doesn't muddy vocals. Case battery is unreal.",
        date: "2026-05-12",
      },
      {
        author: "Priya S.",
        rating: 4,
        title: "Great for the price",
        body: "Fit is secure for runs. Wish the app had more EQ presets but sound is fantastic out of the box.",
        date: "2026-04-28",
      },
    ],
  },
  {
    id: "p2",
    slug: "airwave-pods-neo",
    name: "Airwave Pods Neo",
    category: "earbuds",
    tagline: "Everyday wireless, elevated.",
    description:
      "Lightweight true-wireless earbuds with ENx call clarity, low-latency gaming mode and a 40-hour battery — the daily driver that just works.",
    priceINR: 1799,
    priceUSD: 29,
    mrpINR: 3990,
    mrpUSD: 59,
    rating: 4.5,
    reviewCount: 5120,
    colors: [
      { name: "Midnight", hex: "#14161B" },
      { name: "Mint", hex: "#5FD3B2" },
      { name: "Coral", hex: "#FF6B5E" },
    ],
    features: ["ENx call noise cut", "40h battery", "50ms low latency", "Fast charge 10min=180min"],
    specs: [
      { label: "Driver", value: "10mm dynamic" },
      { label: "Battery", value: "8h + 32h case" },
      { label: "Bluetooth", value: "5.3" },
      { label: "Water resist", value: "IPX4" },
    ],
    badges: ["Low latency"],
    render: "earbuds",
    bestseller: true,
    reviews: [
      {
        author: "Rohan K.",
        rating: 5,
        title: "Best budget buds",
        body: "Latency in games is basically gone. Calls are crisp even on windy days.",
        date: "2026-06-02",
      },
      {
        author: "Neha T.",
        rating: 4,
        title: "Comfortable all day",
        body: "Barely feel them in. Battery easily lasts my week of commutes.",
        date: "2026-03-19",
      },
    ],
  },
  {
    id: "p3",
    slug: "airwave-pods-sport",
    name: "Airwave Pods Sport",
    category: "earbuds",
    tagline: "Built to outlast the workout.",
    description:
      "Sweat-proof earbuds with secure ear-hooks, punchy bass and IPX7 protection — engineered to survive every rep, sprint and downpour.",
    priceINR: 2499,
    priceUSD: 39,
    mrpINR: 4499,
    mrpUSD: 65,
    rating: 4.4,
    reviewCount: 1830,
    colors: [
      { name: "Volt", hex: "#C6F24E" },
      { name: "Stealth", hex: "#1A1C22" },
      { name: "Blaze Red", hex: "#EE1C25" },
    ],
    features: ["IPX7 sweat-proof", "Secure ear-hooks", "38h battery", "BassBoost drivers"],
    specs: [
      { label: "Driver", value: "12mm bass" },
      { label: "Battery", value: "8h + 30h case" },
      { label: "Fit", value: "Ear-hook" },
      { label: "Water resist", value: "IPX7" },
    ],
    badges: ["IPX7"],
    render: "earbuds",
    reviews: [
      {
        author: "Kabir D.",
        rating: 5,
        title: "They don't move",
        body: "Ran a half marathon in the rain — zero slippage, zero water issues.",
        date: "2026-05-30",
      },
      {
        author: "Isha R.",
        rating: 4,
        title: "Great gym buds",
        body: "Bass is motivating. Hooks take a day to get used to but then they vanish.",
        date: "2026-02-11",
      },
    ],
  },
  {
    id: "p4",
    slug: "surge-wireless",
    name: "Surge Wireless",
    category: "headphones",
    tagline: "Over-ear power. 70-hour stamina.",
    description:
      "Full-size wireless headphones with 40mm signature drivers, plush memory-foam cushions and a colossal 70-hour battery for the longest sessions.",
    priceINR: 2999,
    priceUSD: 45,
    mrpINR: 5999,
    mrpUSD: 89,
    rating: 4.6,
    reviewCount: 3402,
    colors: [
      { name: "Carbon", hex: "#1C1F26" },
      { name: "Blaze Red", hex: "#EE1C25" },
      { name: "Sand", hex: "#D9C7A8" },
    ],
    features: ["40mm signature drivers", "70h playback", "Memory-foam cushions", "Dual pairing"],
    specs: [
      { label: "Driver", value: "40mm dynamic" },
      { label: "Battery", value: "70 hours" },
      { label: "Charge", value: "USB-C fast" },
      { label: "Weight", value: "245g" },
    ],
    badges: ["70h battery", "Featured"],
    render: "headphones",
    featured: true,
    reviews: [
      {
        author: "Vikram J.",
        rating: 5,
        title: "Endless battery",
        body: "Charged it once this month. Cushions are cloud-soft for long work sessions.",
        date: "2026-06-14",
      },
      {
        author: "Sara P.",
        rating: 4,
        title: "Rich, warm sound",
        body: "Big soundstage for the price. A touch heavy after hours but very comfy.",
        date: "2026-04-05",
      },
    ],
  },
  {
    id: "p5",
    slug: "surge-lite",
    name: "Surge Lite",
    category: "headphones",
    tagline: "Featherweight. Full sound.",
    description:
      "The lightest over-ear in the lineup at 190g, with 50-hour battery and a bright, energetic tuning made for podcasts, playlists and long calls.",
    priceINR: 1999,
    priceUSD: 32,
    mrpINR: 3999,
    mrpUSD: 59,
    rating: 4.3,
    reviewCount: 2210,
    colors: [
      { name: "Cloud", hex: "#EDEFF3" },
      { name: "Midnight", hex: "#14161B" },
      { name: "Sky", hex: "#5AA9E6" },
    ],
    features: ["Just 190g", "50h battery", "Bright signature", "Foldable design"],
    specs: [
      { label: "Driver", value: "40mm dynamic" },
      { label: "Battery", value: "50 hours" },
      { label: "Weight", value: "190g" },
      { label: "Fold", value: "Flat-fold" },
    ],
    badges: ["Lightweight"],
    render: "headphones",
    bestseller: true,
    reviews: [
      {
        author: "Ananya G.",
        rating: 4,
        title: "So light",
        body: "Forget I'm wearing them on long calls. Clamp is gentle.",
        date: "2026-05-08",
      },
      {
        author: "Dev A.",
        rating: 4,
        title: "Clean vocals",
        body: "Podcasts sound superb. Bass is modest but tight.",
        date: "2026-03-27",
      },
    ],
  },
  {
    id: "p6",
    slug: "pulse-studio",
    name: "Pulse Studio",
    category: "headphones",
    tagline: "Reference-tuned for creators.",
    description:
      "Studio-leaning wireless headphones with a flatter, honest frequency response, low-latency wired mode and a detachable boom-ready mic input.",
    priceINR: 3499,
    priceUSD: 54,
    mrpINR: 6499,
    mrpUSD: 95,
    rating: 4.5,
    reviewCount: 980,
    colors: [
      { name: "Studio Black", hex: "#101216" },
      { name: "Graphite", hex: "#3A3F49" },
    ],
    features: ["Reference tuning", "Wired low-latency mode", "55h wireless", "Swappable cushions"],
    specs: [
      { label: "Driver", value: "42mm dynamic" },
      { label: "Battery", value: "55 hours" },
      { label: "Wired", value: "3.5mm + USB-C" },
      { label: "Weight", value: "260g" },
    ],
    badges: ["Creator pick"],
    render: "headphones",
    reviews: [
      {
        author: "Manish V.",
        rating: 5,
        title: "Honest sound",
        body: "Mixes translate well. The wired mode is clutch for editing video.",
        date: "2026-06-01",
      },
      {
        author: "Tara N.",
        rating: 4,
        title: "Comfortable & neutral",
        body: "Not for bassheads — that's the point. Great for monitoring.",
        date: "2026-04-22",
      },
    ],
  },
  {
    id: "p7",
    slug: "nirvana-elite-anc",
    name: "Nirvana Elite ANC",
    category: "premium",
    tagline: "Hybrid ANC. Total silence.",
    description:
      "The flagship: hybrid active noise cancellation with 6 mics, LDAC-grade wireless detail, adaptive transparency and premium metal-and-vegan-leather build.",
    priceINR: 7999,
    priceUSD: 119,
    mrpINR: 14999,
    mrpUSD: 219,
    rating: 4.8,
    reviewCount: 1540,
    colors: [
      { name: "Onyx", hex: "#0F1115" },
      { name: "Champagne", hex: "#C8A96A" },
      { name: "Blaze Red", hex: "#EE1C25" },
    ],
    features: ["Hybrid ANC (6 mics)", "Hi-Res wireless", "Adaptive transparency", "Metal build"],
    specs: [
      { label: "Driver", value: "40mm hi-res" },
      { label: "ANC", value: "Hybrid, up to 42dB" },
      { label: "Battery", value: "40h (ANC on)" },
      { label: "Codec", value: "Hi-Res / AAC" },
    ],
    badges: ["Flagship", "Hi-Res"],
    render: "headphones",
    featured: true,
    bestseller: true,
    reviews: [
      {
        author: "Arjun B.",
        rating: 5,
        title: "Airplane silence",
        body: "Cabin roar just disappears. Build feels genuinely premium in hand.",
        date: "2026-06-20",
      },
      {
        author: "Meera K.",
        rating: 5,
        title: "Worth every rupee",
        body: "Detail retrieval is a step above anything I've owned near this price.",
        date: "2026-05-15",
      },
    ],
  },
  {
    id: "p8",
    slug: "nirvana-one",
    name: "Nirvana One",
    category: "premium",
    tagline: "Premium ANC, simplified.",
    description:
      "Everyday premium: clean active noise cancellation, plush comfort and a warm, refined tuning in a lighter, more affordable package than the Elite.",
    priceINR: 5499,
    priceUSD: 85,
    mrpINR: 9999,
    mrpUSD: 149,
    rating: 4.6,
    reviewCount: 1120,
    colors: [
      { name: "Onyx", hex: "#0F1115" },
      { name: "Slate", hex: "#5B6270" },
    ],
    features: ["Active noise cancellation", "Warm signature", "45h battery", "Plush comfort"],
    specs: [
      { label: "Driver", value: "40mm dynamic" },
      { label: "ANC", value: "Up to 35dB" },
      { label: "Battery", value: "45h (ANC on)" },
      { label: "Weight", value: "255g" },
    ],
    badges: ["ANC"],
    render: "headphones",
    reviews: [
      {
        author: "Farhan S.",
        rating: 5,
        title: "Cozy and quiet",
        body: "Perfect WFH companion. ANC is plenty for a noisy household.",
        date: "2026-05-19",
      },
      {
        author: "Divya M.",
        rating: 4,
        title: "Warm and easy",
        body: "Non-fatiguing sound for long listening. Comfortable clamp.",
        date: "2026-03-30",
      },
    ],
  },
  {
    id: "p9",
    slug: "stone-blast",
    name: "Stone Blast",
    category: "speakers",
    tagline: "Room-filling. Rain-or-shine.",
    description:
      "A portable Bluetooth speaker with dual passive radiators, 24W of stereo output, IPX7 waterproofing and stereo-pairing to double the wall of sound.",
    priceINR: 3299,
    priceUSD: 49,
    mrpINR: 5999,
    mrpUSD: 89,
    rating: 4.6,
    reviewCount: 2670,
    colors: [
      { name: "Blaze Red", hex: "#EE1C25" },
      { name: "Carbon", hex: "#1C1F26" },
      { name: "Teal", hex: "#1FA6A0" },
    ],
    features: ["24W stereo output", "Dual passive radiators", "IPX7 waterproof", "TWS stereo pairing"],
    specs: [
      { label: "Output", value: "24W RMS" },
      { label: "Battery", value: "16 hours" },
      { label: "Water resist", value: "IPX7" },
      { label: "Pairing", value: "TWS stereo" },
    ],
    badges: ["IPX7", "24W"],
    render: "speaker",
    bestseller: true,
    reviews: [
      {
        author: "Nikhil P.",
        rating: 5,
        title: "Huge for its size",
        body: "Took it to the pool — floats, survives splashes, and it's LOUD.",
        date: "2026-06-09",
      },
      {
        author: "Ritika S.",
        rating: 4,
        title: "Great party speaker",
        body: "Paired two for stereo and it filled the terrace easily.",
        date: "2026-04-14",
      },
    ],
  },
  {
    id: "p10",
    slug: "stone-mini",
    name: "Stone Mini",
    category: "speakers",
    tagline: "Pocket-size, big on punch.",
    description:
      "An ultra-portable 8W speaker with a surprising low-end, clip-on loop and 12-hour battery — the everywhere-you-go sound companion.",
    priceINR: 1299,
    priceUSD: 19,
    mrpINR: 2499,
    mrpUSD: 35,
    rating: 4.3,
    reviewCount: 3910,
    colors: [
      { name: "Charcoal", hex: "#1A1C22" },
      { name: "Blaze Red", hex: "#EE1C25" },
      { name: "Lemon", hex: "#F2C94C" },
    ],
    features: ["8W driver", "12h battery", "Clip-on loop", "IPX6 splash-proof"],
    specs: [
      { label: "Output", value: "8W" },
      { label: "Battery", value: "12 hours" },
      { label: "Water resist", value: "IPX6" },
      { label: "Weight", value: "220g" },
    ],
    badges: ["Portable"],
    render: "speaker",
    reviews: [
      {
        author: "Ayaan H.",
        rating: 4,
        title: "Tiny but mighty",
        body: "Clips to my backpack for hikes. Bass is shockingly present.",
        date: "2026-05-21",
      },
      {
        author: "Sneha L.",
        rating: 4,
        title: "Great gift",
        body: "Bought three as gifts. Everyone loved the size and volume.",
        date: "2026-02-28",
      },
    ],
  },
  {
    id: "p11",
    slug: "vantage-watch",
    name: "Vantage Watch",
    category: "smartwatches",
    tagline: "Your day, on your wrist.",
    description:
      "A 1.9” AMOLED smartwatch with Bluetooth calling, 100+ sport modes, SpO2 and heart-rate tracking, and a 7-day battery in a premium aluminium frame.",
    priceINR: 3999,
    priceUSD: 62,
    mrpINR: 8999,
    mrpUSD: 129,
    rating: 4.5,
    reviewCount: 4300,
    colors: [
      { name: "Space Grey", hex: "#2A2D34" },
      { name: "Silver", hex: "#C9CDD4" },
      { name: "Rose", hex: "#E8A0A6" },
    ],
    features: ["1.9” AMOLED", "Bluetooth calling", "100+ sport modes", "7-day battery"],
    specs: [
      { label: "Display", value: '1.9" AMOLED' },
      { label: "Battery", value: "7 days" },
      { label: "Sensors", value: "HR + SpO2" },
      { label: "Water resist", value: "IP68" },
    ],
    badges: ["BT Calling", "Featured"],
    render: "watch",
    featured: true,
    reviews: [
      {
        author: "Harsh V.",
        rating: 5,
        title: "Bright, snappy display",
        body: "AMOLED is gorgeous outdoors. Calls on the wrist actually work well.",
        date: "2026-06-11",
      },
      {
        author: "Pooja R.",
        rating: 4,
        title: "Battery champ",
        body: "Genuinely lasts a week with tracking on. Great value.",
        date: "2026-04-18",
      },
    ],
  },
  {
    id: "p12",
    slug: "vantage-fit",
    name: "Vantage Fit",
    category: "smartwatches",
    tagline: "Lightweight tracker, serious data.",
    description:
      "A slim fitness-first smartwatch with continuous heart-rate, sleep staging, stress tracking and a feathery build you'll forget you're wearing.",
    priceINR: 2499,
    priceUSD: 39,
    mrpINR: 4999,
    mrpUSD: 75,
    rating: 4.2,
    reviewCount: 2050,
    colors: [
      { name: "Obsidian", hex: "#16181D" },
      { name: "Blaze Red", hex: "#EE1C25" },
      { name: "Ice", hex: "#DDE7EE" },
    ],
    features: ["Continuous HR", "Sleep staging", "Stress tracking", "10-day battery"],
    specs: [
      { label: "Display", value: '1.6" AMOLED' },
      { label: "Battery", value: "10 days" },
      { label: "Sensors", value: "HR + sleep" },
      { label: "Weight", value: "28g" },
    ],
    badges: ["Fitness"],
    render: "watch",
    reviews: [
      {
        author: "Gaurav T.",
        rating: 4,
        title: "Set and forget",
        body: "Sleep data is detailed and the battery just keeps going.",
        date: "2026-05-26",
      },
      {
        author: "Lisa F.",
        rating: 4,
        title: "Barely there",
        body: "So light I wear it 24/7. Step tracking is accurate enough for me.",
        date: "2026-03-09",
      },
    ],
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelated(slug: string, limit = 3): Product[] {
  const current = getProduct(slug);
  if (!current) return PRODUCTS.slice(0, limit);
  return PRODUCTS.filter(
    (p) => p.slug !== slug && p.category === current.category
  )
    .concat(PRODUCTS.filter((p) => p.slug !== slug && p.category !== current.category))
    .slice(0, limit);
}

export const FEATURED = PRODUCTS.filter((p) => p.featured);
export const BESTSELLERS = PRODUCTS.filter((p) => p.bestseller);
